image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: "ubuntu"
                SERVER: "ec2-13-250-122-124.ap-southeast-1.compute.amazonaws.com"
                COMMAND: "/home/ubuntu/unicert/nft-display/./deploy.sh"